baseURL = "https://jimmerlitter.com/"
title = "James Huang"
theme = "PaperMod"
locale = "en-us"
enableRobotsTXT = true

[params]
  defaultTheme = "auto"
  showReadingTime = true
  showWordCount = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowFullTextinRSS = true

  [params.profileMode]
    enabled = true
    title = "James Huang"
    subtitle = "ECE @ UCSD · Robotics · Buisness Development · Startups"
    imageUrl = "/images/profile.jpg"
    imageTitle = "James Huang"
    imageWidth = 120
    imageHeight = 120

    [[params.profileMode.buttons]]
      name = "Blog"
      url = "posts"

    [[params.profileMode.buttons]]
      name = "Books"
      url = "books"

    [[params.profileMode.buttons]]
      name = "Athletic"
      url = "athletic"

    [[params.profileMode.buttons]]
      name = "Creative"
      url = "creative"

    [[params.profileMode.buttons]]
      name = "About"
      url = "about"

    [[params.profileMode.buttons]]
      name = "Resume"
      url = "James-Huang-Resume.pdf"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/JimmerLitter"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/jameshuanger/"

  [[params.socialIcons]]
    name = "x"
    url = "https://x.com/jamestuffdemon"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "books"
    name = "Books"
    url = "/books/"
    weight = 20

  [[menu.main]]
    identifier = "athletic"
    name = "Athletic"
    url = "/athletic/"
    weight = 30

  [[menu.main]]
    identifier = "creative"
    name = "Creative"
    url = "/creative/"
    weight = 40

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 50

  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/James-Huang-Resume.pdf"
    weight = 60

[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false
  [markup.highlight]
    noClasses = false
