baseURL = "https://jimmerlitter.com/"
title = "James Huang"
theme = "PaperMod"
locale = "en-us"
enableRobotsTXT = true

[params]
  defaultTheme = "auto"
  showReadingTime = true
  showWordCount = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowFullTextinRSS = true
  ShowToc = true
  TocOpen = false
  comments = true

  [params.profileMode]
    enabled = true
    title = "James Huang"
    subtitle = "ECE @ UCSD · Robotics · Buisness Development"
    imageUrl = "/images/profile.jpg"
    imageTitle = "James Huang"
    imageWidth = 120
    imageHeight = 120

    [[params.profileMode.buttons]]
      name = "Blog"
      url = "posts"

    [[params.profileMode.buttons]]
      name = "About"
      url = "about"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/JimmerLitter"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/jameshuanger/"

  [[params.socialIcons]]
    name = "x"
    url = "https://x.com/jamestuffdemon"

  [params.giscus]
    repo = "JimmerLitter/JimmerLitter-Personal-Website"
    repoId = "R_kgDOTQ5GlA"
    category = "Announcements"
    categoryId = "DIC_kwDOTQ5GlM4DAvOw"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20

[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false
  [markup.highlight]
    noClasses = false
